# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb6b3b3ca1d886cee74076bf63296376f696c8477115f7a6105e194093733da4e31f20100df4f946882731fd837ee1561aa1b55c2bd3376e707a00a16059047f

test:
  secret_key_base: 52a2c075117071a182ce1faec4d7966c0d2a9a699c8770e9645c5270ed1b8729c774dff78f997305b65defd149b989a2a3e37e5e87375c573faf666753f7dd2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
